version: "3.9"

services:
  reverse-proxy:
    deploy:
      replicas: 0

  api:
    ports:
      - "127.0.0.1:4051:4000"

  web:
    ports:
      - "127.0.0.1:3002:3000"

  grafana:
    ports:
      - "127.0.0.1:3900:3000"
